version: '3.1'

services:

  dbserver:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: webnews
      MYSQL_USER: webnews
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - webnews_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - dbserver
    environment:
      PMA_ARBITRARY: 1
    networks:
      - webnews_network

  rabbit:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - webnews_network

  backend:
    build:
      context: backend
    image: webnews/backend:latest
    ports:
      - 5000:5000
    depends_on:
      - dbserver
      - rabbit
    environment:
      FLASK_APP: "webnews.py"
      FLASK_DEBUG: "0"
      SECRET_KEY: ${SECRET_KEY}
      X_RAPID_API_KEY: ${X_RAPID_API_KEY}
      DATABASE_URL: "mysql+pymysql://webnews:${MYSQL_PASSWORD}@dbserver/webnews"
      PRODUCTION_MODE: "yes"
      TZ: "Europe/Zurich"
    networks:
      - webnews_network

  scheduler:
    build:
      context: jobs
    image: webnews/jobs:latest
    ports:
      - 5555:5555
    depends_on:
      - backend
    environment:
      NEWS_API_KEY: ${NEWS_API_KEY}
      JOBS_APP_TOKEN: ${JOBS_APP_TOKEN}
      JOBS_APP_NAME: webnews.jobs
      WEBNEWS_API_BASE_URL: http://backend:5000/api/v1.0
      CELERY_BROKER_URL: amqp://admin:admin@rabbit:5672//
      CELERY_BACKEND_URL: rpc://
      TZ: "Europe/Zurich"
    networks:
      - webnews_network

  frontend:
    build:
      context: frontend
      args:
        FRONTEND_APP_TOKEN: ${FRONTEND_APP_TOKEN}
        FRONTEND_APP_NAME: webnews.frontend
        WEBNEWS_API_BASE_URL: http://backend:5000/api/v1.0
    image: webnews/frontend:latest
    ports:
      - 8080:80
    depends_on:
      - scheduler
    environment:
      TZ: "Europe/Zurich"
    networks:
      - webnews_network

networks:
  webnews_network:
    driver: bridge

volumes:
  mysqldata:
