name: build-frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd frontend/webnews
        npm install

    - name: Install ng cli
      run: |
        cd frontend/webnews
        npm install -g @angular/cli

    - name: Lint project
      run: ng lint

    - name: Build project
      run: |
        cd frontend/webnews
        ng build

#    - name: Run tests
#      run: ng test
